name: Build and deploy application

on:
    push:
        branches:
            - master

env:
    DOCKER_IMAGE_NAME: azzazkhan/image-transformation-proxy

jobs:
    update:
        name: Build and push image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USER }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push image to registry
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: |
                      ${{ env.DOCKER_IMAGE_NAME }}:latest
                      ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
                  cache-from: |
                      type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:latest
                      type=gha,scope=${{ github.workflow }}
                  cache-to: type=gha,scope=${{ github.workflow }},mode=max
